sudo: required
services:
  - docker

#construir imagen temporal
before_install:
  - docker build -t lophophoro/dev -f ./client/Dockerfile.dev ./client

#correr tests
script:
  - docker run -e CI=true lophophoro/dev npm test

#si todo va bien, crear imagen para produccion
after_success:
  - docker build -t lophophoro/multi-client ./client
  - docker build -t lophophoro/multi-nginx ./nginx
  - docker build -t lophophoro/multi-server ./server
  - docker build -t lophophoro/multi-worker ./worker

  #loggear en el docker CLI, para subir las imagenes a dockerhub en vez de subirlas a ELASTIC BEANSTALK directamente
  #echo "$DOCKER_PASSWORD" recibe la variable de entorno (establecidas en travis), y la pasa como parametro a docker login -u "$DOCKER_ID" a traves de --password-stdin
  # el flag -u es para "user"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #subir imagenes a travis
  - docker push lophophoro/multi-client
  - docker push lophophoro/multi-nginx
  - docker push lophophoro/multi-server
  - docker push lophophoro/multi-worker
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "multi-docker"
#   env: "MultiDocker-env"
#   bucket_name: "elasticbeanstalk-us-east-2-121607027350"
#   bucket_path: "docker-multi"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
